name: ci

on:
  push:
    branches:
      - main
jobs:
  converttopdf:
    name: Build PDF
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: docs
          output_dir: .
          build_html: false
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: docs
          path: .

  deploy:
    permissions:
      contents: write
      deployments: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

