name: ci

on:
  push:
    branches:
      - main
jobs:

  deploy:
    permissions:
      contents: write
      deployments: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
